config/routes.rb
Rails.application.routes.draw do
  resources :geems do
    member do
      get 'confirm'
    end
  end
  resources :links do
    member do
      get 'confirm'
    end
  end
  resources :commands do
    member do
      get 'confirm'
    end
  end
  
  use_doorkeeper do
    controllers applications: 'oauth/applications',
                authorized_applications: 'oauth/authorized_applications'
  end
  # devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }

  devise_for :users, path: 'account', controllers: {
    registrations: :account,
    sessions: :sessions,
    passwords: :passwords,
    omniauth_callbacks: 'auth/omniauth_callbacks'
  }
  # get 'cur_page', to: 'application#page'
  root to: 'application#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def first_error_message
    errors.messages.values.first.first
  end
end

app/models/command.rb
class Command < ApplicationRecord
  validates :content, uniqueness: { case_sensitive: false, message: "已存在相同内容的指令" }
end

app/models/geem.rb
class Geem < ApplicationRecord
  validates :name, uniqueness: { case_sensitive: false, message: "已存在相同名称的gem" }
end

app/models/link.rb
class Link < ApplicationRecord
  validates :content, uniqueness: { case_sensitive: false, message: "已存在相同内容的链接" }
end

app/models/setting.rb
# frozen_string_literal: true
# RailsSettings Model
class Setting < RailsSettings::Base
  source Rails.root.join("config/config.yml")
end

app/models/user.rb
class User < ApplicationRecord
	ACCESSABLE_ATTRS = %i(name email current_password password password_confirmation _rucaptcha)

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :commands
  has_many :links
  has_many :geems

  class << self
  end
end

app/controllers/account_controller.rb
class AccountController < Devise::RegistrationsController
	layout 'login'

	def new
		super
	end

	def create
		build_resource(sign_up_params)
    resource.name = params[resource_name][:name]
    resource.email = params[resource_name][:email]
    if verify_rucaptcha?(resource) && resource.save
      sign_in(resource_name, resource)
    end
	end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception

  before_action do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
    
    if devise_controller?
      devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(*User::ACCESSABLE_ATTRS) }
      devise_parameter_sanitizer.permit(:account_update) do |u|
        if current_user.email_locked?
          u.permit(*User::ACCESSABLE_ATTRS)
        else
          u.permit(:email, *User::ACCESSABLE_ATTRS)
        end
      end
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(*User::ACCESSABLE_ATTRS) }
    end
  end

  before_action :authenticate_user!

  def home
  end

  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end

  # def current_user
  #   if doorkeeper_token
  #     return @current_user if defined? @current_user
  #     @current_user ||= User.find_by_id(doorkeeper_token.resource_owner_id)
  #     sign_in @current_user
  #     @current_user
  #   else
  #     super
  #   end
  # end

  protected
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  before_action :set_command, only: [:show, :edit, :update, :confirm, :destroy]
  before_action :set_data_href, only: %i(update destroy)
  respond_to :html, :json
  layout false, only: %i(new edit confirm)

  def index
    @commands = current_user.commands
    respond_with(@commands)
  end

  def show
    respond_with(@command)
  end

  def new
    @command = Command.new
    respond_with(@command)
  end

  def edit
  end

  def create
    @command = Command.new(command_params)
    @command.save
  end

  def update
    @command.update(command_params)
  end

  def confirm
  end

  def destroy
    @command.destroy
  end

  private
    def set_command
      @command = Command.find(params[:id])
    end

    def command_params
      params[:command][:user_id] = current_user.id
      params[:command].permit(:content, :use_for, :labels, :user_id)
    end

    def set_data_href
      @data_href = edit_command_path(@command)
    end
end

app/controllers/geems_controller.rb
class GeemsController < ApplicationController
  before_action :set_geem, only: [:show, :edit, :update, :confirm, :destroy]
  before_action :set_data_href, only: %i(update destroy)
  respond_to :html, :json
  layout false, only: %i(new edit confirm)

  def index
    @geems = current_user.geems
    respond_with(@geems)
  end

  def show
    respond_with(@geem)
  end

  def new
    @geem = Geem.new
    respond_with(@geem)
  end

  def edit
  end

  def create
    @geem = Geem.new(geem_params)
    @geem.save
  end

  def update
    @geem.update(geem_params)
  end

  def confirm
  end

  def destroy
    @geem.destroy
  end

  private
    def set_geem
      @geem = Geem.find(params[:id])
    end

    def geem_params
      params[:geem][:user_id] = current_user.id
      params[:geem].permit(:name, :use_for, :url, :labels, :user_id)
    end

    def set_data_href
      @data_href = edit_geem_path(@geem)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :confirm, :destroy]
  before_action :set_data_href, only: %i(update destroy)
  respond_to :html, :json
  layout false, only: %i(new edit confirm)

  def index
    @links = current_user.links
    respond_with(@links)
  end

  def show
    respond_with(@link)
  end

  def new
    @link = Link.new
    respond_with(@link)
  end

  def edit
  end

  def create
    @link = Link.new(link_params)
    @link.save
  end

  def update
    @link.update(link_params)
  end

  def confirm
  end

  def destroy
    @link.destroy
  end

  private
    def set_link
      @link = Link.find(params[:id])
    end

    def link_params
      params[:link][:user_id] = current_user.id
      params[:link].permit(:content, :use_for, :labels, :user_id)
    end

    def set_data_href
      @data_href = edit_link_path(@link)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController
	layout 'login'

	def new
		super
	end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < Devise::SessionsController
  skip_before_action :authenticate_user!

  layout 'login'

  def new
    super
  end

  def create
    super
  end

  def destroy
    super
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
	THEME = 'theme-'.freeze

	def title_tag(str)
    content_for :title, raw("#{str} · #{Setting.app_name}")
  end

  def modal_title_tag(str)
    content_for :modal_title, raw("#{str}")
  end

  def active_state(color)
  	cookies[:skins] ||= "red"
  	cookies[:skins] == color ? "active" : ''
  end

  def current_theme
  	THEME + (cookies[:skins] || "red")
  end
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/helpers/geems_helper.rb
module GeemsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/views/commands/_form.html.erb
<%= simple_form_for(@command, remote: true, html: {id: "form_validation"}) do |f| %>
  <%= f.input :content, label: '指令内容', wrapper: :form_float_required %>
  <%= f.input :use_for, label: '指令用途', wrapper: :form_float_required %>
  <label for="command_labels">指令标签</label>
  <%= f.input :labels, wrapper: :vertical_tag %>
  <%= f.button :submit, '提交', class: 'btn btn-block btn-lg btn-primary waves-effect' %>
<% end %>

app/views/commands/_show.html.erb
<% command ||= @command %>
<tr>
  <td><%= command.content %><button class="clipboard-btn" type="button" data-clipboard-text="<%= command.content %>"><%= image_tag("clippy.svg", size: '16x18', alt: "copy") %></button></td>
  <td><%= command.use_for %></td>
  <td><%= command.labels %></td>
  <td><button type="button" class="no_style_btn" data-toggle="modal" data-target="#defaultModal" data-text='编辑指令' data-href=<%= edit_command_path(command) %> data-method='GET' ><%= material_icon.mode_edit %></button></td>
  <td><button type="button" class="no_style_btn" data-toggle="modal" data-target="#defaultModal" data-text='指令删除后无法恢复，确定删除吗？' data-href=<%= confirm_command_path(command) %> data-method='GET' ><%= material_icon.delete %></button></td>
</tr>

app/views/commands/confirm.html.erb
<%= simple_form_for(@command, remote: true, html: {id: "form_validation"}) do |f| %>
  <%= f.input :content, label: '指令内容', disabled: true, wrapper: :form_float_required %>
  <%= f.input :use_for, label: '指令用途', disabled: true, wrapper: :form_float_required %>
  <label for="command_labels">指令标签</label>
  <%= f.input :labels, disabled: true, wrapper: :vertical_tag %>
<% end %>
<button type="button" class="btn btn-block btn-lg waves-effect" data-dismiss="modal">不，点错了</button>
<%= link_to '确定，删除', command_path(@command), method: 'DELETE', remote: true, class: "btn btn-block btn-lg btn-warning waves-effect" %>

app/views/commands/create.js.erb
$("#defaultModal").modal("hide");
<% if @command.errors.empty? %>
  notify('指令创建成功');
  datatableCreate(removeTags('<%= j render('show') %>'))
<% else %>
  var text = '指令创建失败: ' + '<%= @command.first_error_message %>'
  notify(text);
<% end %>

app/views/commands/index.html.erb
<div class="container-fluid">
  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header">
          <h2>
            <%= t("menu.cmd") %>
            <button type="button" class="btn btn-primary waves-effect pull-right" data-toggle="modal" data-target="#defaultModal" data-text='新增指令' data-href=<%= new_command_path %> data-method='GET' >新增指令</button>
          </h2>
        </div>
        <div class="body">
          <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover js-table dataTable">
              <thead>
                <tr>
                    <th>指令内容</th>
                    <th>指令用途</th>
                    <th>指令标签</th>
                    <th>编辑</th>
                    <th>删除</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                    <th>指令内容</th>
                    <th>指令用途</th>
                    <th>指令标签</th>
                    <th>编辑</th>
                    <th>删除</th>
                </tr>
              </tfoot>
              <tbody>
                <% @commands.each do |command| %>
                  <tr>
                    <td><%= command.content %><button class="clipboard-btn" type="button" data-clipboard-text="<%= command.content %>"><%= image_tag("clippy.svg", size: '16x18', alt: "copy") %></button></td>
                    <td><%= command.use_for %></td>
                    <td><%= command.labels %></td>
                    <td><button type="button" class="no_style_btn" data-toggle="modal" data-target="#defaultModal" data-text='编辑指令' data-href=<%= edit_command_path(command) %> data-method='GET' ><%= material_icon.mode_edit %></button></td>
                    <td><button type="button" class="no_style_btn" data-toggle="modal" data-target="#defaultModal" data-text='指令删除后无法恢复，确定删除吗？' data-href=<%= confirm_command_path(command) %> data-method='GET' ><%= material_icon.delete %></button></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/commands/update.js.erb
$("#defaultModal").modal("hide")
<% if @command.errors.empty? %>
  notify('指令更新成功');
  datatableUpdate(removeTags('<%= j render('show') %>'), $("[data-href='<%= @data_href %>']").parent().parent())
<% else %>
  var text = '指令更新失败: ' + '<%= @command.first_error_message %>'
  notify(text);
<% end %>

app/views/geems/_form.html.erb
<%= simple_form_for(@geem, remote: true, html: {id: "form_validation"}) do |f| %>
  <%= f.input :name, label: 'gem名称', wrapper: :form_float_required %>
  <%= f.input :use_for, label: 'gem用途', wrapper: :form_float_required %>
  <%= f.input :url, label: 'gem——url', wrapper: :form_float_required %>
  <label for="geem_labels">gem标签</label>
  <%= f.input :labels, wrapper: :vertical_tag %>
  <%= f.button :submit, '提交', class: 'btn btn-block btn-lg btn-primary waves-effect' %>
<% end %>

app/views/geems/_show.html.erb
<% geem ||= @geem %>
<tr>
  <td><%= link_to geem.name, geem.url, target: "_blank"%><button class="clipboard-btn" type="button" data-clipboard-text="<%= geem.url %>"><%= image_tag("clippy.svg", size: '16x18', alt: "copy") %></button></td>
  <td><%= geem.use_for %></td>
  <td><%= geem.labels %></td>
  <td><button type="button" class="no_style_btn" data-toggle="modal" data-target="#defaultModal" data-text='编辑指令' data-href=<%= edit_geem_path(geem) %> data-method='GET' ><%= material_icon.mode_edit %></button></td>
  <td><button type="button" class="no_style_btn" data-toggle="modal" data-target="#defaultModal" data-text='指令删除后无法恢复，确定删除吗？' data-href=<%= confirm_geem_path(geem) %> data-method='GET' ><%= material_icon.delete %></button></td>
</tr>

app/views/geems/confirm.html.erb
<%= simple_form_for(@geem, remote: true, html: {id: "form_validation"}) do |f| %>
  <%= f.input :name, label: 'gem名称', disabled: true, wrapper: :form_float_required %>
  <%= f.input :use_for, label: 'gem用途', disabled: true, wrapper: :form_float_required %>
  <%= f.input :url, label: 'gem——url', disabled: true, wrapper: :form_float_required %>
  <label for="geem_labels">gem标签</label>
  <%= f.input :labels, disabled: true, wrapper: :vertical_tag %>
<% end %>
<button type="button" class="btn btn-block btn-lg waves-effect" data-dismiss="modal">不，点错了</button>
<%= link_to '确定，删除', geem_path(@geem), method: 'DELETE', remote: true, class: "btn btn-block btn-lg btn-warning waves-effect" %>

app/views/geems/create.js.erb
$("#defaultModal").modal("hide");
<% if @geem.errors.empty? %>
  notify('gem创建成功');
  datatableCreate(removeTags('<%= j render('show') %>'))
<% else %>
  var text = 'gem创建失败: ' + '<%= @geem.first_error_message %>'
  notify(text);
<% end %>

app/views/geems/destroy.js.erb
notify('gem删除成功');
$("#defaultModal").modal("hide");
$('.js-table').DataTable().row($("[data-href='<%= @data_href %>']").parent().parent()).remove().draw();

app/views/geems/edit.html.erb
<%= render 'form' %>

app/views/geems/index.html.erb
<div class="container-fluid">
  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header">
          <h2>
            <%= t("menu.geem") %>
            <button type="button" class="btn btn-primary waves-effect pull-right" data-toggle="modal" data-target="#defaultModal" data-text='新增gem' data-href=<%= new_geem_path %> data-method='GET' >新增gem</button>
          </h2>
        </div>
        <div class="body">
          <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover js-table dataTable">
              <thead>
                <tr>
                    <th>gem名称</th>
                    <th>gem用途</th>
                    <th>gem标签</th>
                    <th>编辑</th>
                    <th>删除</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                    <th>gem名称</th>
                    <th>gem用途</th>
                    <th>gem标签</th>
                    <th>编辑</th>
                    <th>删除</th>
                </tr>
              </tfoot>
              <tbody>
                <% @geems.each do |geem| %>
                  <tr>
                    <td><%= link_to geem.name, geem.url,target: "_blank"%><button class="clipboard-btn" type="button" data-clipboard-text="<%= geem.url %>"><%= image_tag("clippy.svg", size: '16x18', alt: "copy") %></button></td>
                  <td><%= geem.use_for %></td>
                  <td><%= geem.labels %></td>
                  <td><button type="button" class="no_style_btn" data-toggle="modal" data-target="#defaultModal" data-text='编辑指令' data-href=<%= edit_geem_path(geem) %> data-method='GET' ><%= material_icon.mode_edit %></button></td>
                  <td><button type="button" class="no_style_btn" data-toggle="modal" data-target="#defaultModal" data-text='指令删除后无法恢复，确定删除吗？' data-href=<%= confirm_geem_path(geem) %> data-method='GET' ><%= material_icon.delete %></button></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/geems/new.html.erb
<%= render 'form' %>

app/views/geems/update.js.erb
$("#defaultModal").modal("hide")
<% if @geem.errors.empty? %>
  notify('gem更新成功');
  datatableUpdate(removeTags('<%= j render('show') %>'), $("[data-href='<%= @data_href %>']").parent().parent())
<% else %>
  var text = 'gem更新失败: ' + '<%= @geem.first_error_message %>'
  notify(text);
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title><%= content_for?(:title) ? yield(:title) : Setting.app_name %></title>
    <%= favicon_link_tag image_path("favicon.ico") %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class=<%= current_theme %> >
    <%= render 'shared/top_nav' %>
    <%= render 'shared/left_nav' %>
    <section class="content">
      <%= yield %>
      <%= render 'shared/modal' %>
    </section>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title><%= content_for?(:title) ? yield(:title) : Setting.app_name %></title>
    <%= favicon_link_tag image_path("favicon.ico") %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'login', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= yield %>
</html>

app/views/links/_form.html.erb
<%= simple_form_for(@link, remote: true, html: {id: "form_validation"}) do |f| %>
  <%= f.input :content, label: '链接内容', wrapper: :form_float_required %>
  <%= f.input :use_for, label: '链接用途', wrapper: :form_float_required %>
  <label for="link_labels">链接标签</label>
  <%= f.input :labels, wrapper: :vertical_tag %>
  <%= f.button :submit, '提交', class: 'btn btn-block btn-lg btn-primary waves-effect' %>
<% end %>

app/views/links/_show.html.erb
<% link ||= @link %>
<tr>
  <td><%= link_to link.use_for, link.content, target: "_blank"%><button class="clipboard-btn" type="button" data-clipboard-text="<%= link.content %>"><%= image_tag("clippy.svg", size: '16x18', alt: "copy") %></button></td>
  <td><%= link.labels %></td>
  <td><button type="button" class="no_style_btn" data-toggle="modal" data-target="#defaultModal" data-text='编辑指令' data-href=<%= edit_link_path(link) %> data-method='GET' ><%= material_icon.mode_edit %></button></td>
  <td><button type="button" class="no_style_btn" data-toggle="modal" data-target="#defaultModal" data-text='指令删除后无法恢复，确定删除吗？' data-href=<%= confirm_link_path(link) %> data-method='GET' ><%= material_icon.delete %></button></td>
</tr>

app/views/links/confirm.html.erb
<%= simple_form_for(@link, remote: true, html: {id: "form_validation"}) do |f| %>
  <%= f.input :content, label: '指令内容', disabled: true, wrapper: :form_float_required %>
  <%= f.input :use_for, label: '指令用途', disabled: true, wrapper: :form_float_required %>
  <label for="link_labels">指令标签</label>
  <%= f.input :labels, disabled: true, wrapper: :vertical_tag %>
<% end %>
<button type="button" class="btn btn-block btn-lg waves-effect" data-dismiss="modal">不，点错了</button>
<%= link_to '确定，删除', link_path(@link), method: 'DELETE', remote: true, class: "btn btn-block btn-lg btn-warning waves-effect" %>

app/views/links/create.js.erb
$("#defaultModal").modal("hide");
<% if @link.errors.empty? %>
  notify('指令创建成功');
  datatableCreate(removeTags('<%= j render('show') %>'))
<% else %>
  var text = '指令创建失败: ' + '<%= @link.first_error_message %>'
  notify(text);
<% end %>

app/views/links/destroy.js.erb
notify('指令删除成功');
$("#defaultModal").modal("hide");
$('.js-table').DataTable().row($("[data-href='<%= @data_href %>']").parent().parent()).remove().draw();

app/views/links/edit.html.erb
<%= render 'form' %>

app/views/links/index.html.erb
<div class="container-fluid">
  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header">
          <h2>
            <%= t("menu.link") %>
            <button type="button" class="btn btn-primary waves-effect pull-right" data-toggle="modal" data-target="#defaultModal" data-text='新增链接' data-href=<%= new_link_path %> data-method='GET' >新增链接</button>
          </h2>
        </div>
        <div class="body">
          <div class="table-responsive">
            <table class="table table-bordered table-striped table-hover js-table dataTable">
              <thead>
                <tr>
                    <th>链接用途</th>
                    <th>链接标签</th>
                    <th>编辑</th>
                    <th>删除</th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                    <th>链接用途</th>
                    <th>链接标签</th>
                    <th>编辑</th>
                    <th>删除</th>
                </tr>
              </tfoot>
              <tbody>
                <% @links.each do |link| %>
                  <tr>
                    <td><%= link_to link.use_for, link.content, target: "_blank"%><button class="clipboard-btn" type="button" data-clipboard-text="<%= link.content %>"><%= image_tag("clippy.svg", size: '16x18', alt: "copy") %></button></td>
                    <td><%= link.labels %></td>
                    <td><button type="button" class="no_style_btn" data-toggle="modal" data-target="#defaultModal" data-text='编辑指令' data-href=<%= edit_link_path(link) %> data-method='GET' ><%= material_icon.mode_edit %></button></td>
                    <td><button type="button" class="no_style_btn" data-toggle="modal" data-target="#defaultModal" data-text='指令删除后无法恢复，确定删除吗？' data-href=<%= confirm_link_path(link) %> data-method='GET' ><%= material_icon.delete %></button></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/links/update.js.erb
$("#defaultModal").modal("hide")
<% if @link.errors.empty? %>
  notify('指令更新成功');
  datatableUpdate(removeTags('<%= j render('show') %>'), $("[data-href='<%= @data_href %>']").parent().parent())
<% else %>
  var text = '指令更新失败: ' + '<%= @link.first_error_message %>'
  notify(text);
<% end %>

app/views/shared/_left_nav.html.erb
<section>
  <!-- Left Sidebar -->
  <aside id="leftsidebar" class="sidebar">
    <!-- Menu -->
    <div class="menu">
      <ul class="list">
        <li>
          <%= link_to root_path do %>
            <i class="fas fa-home fa-2x"></i>
            <span><%= t("menu.home")%></span>
          <% end %>
        </li>

        <li>
          <%= link_to commands_path do %>
            <i class="fas fa-terminal fa-2x"></i>
            <span><%= t("menu.cmd") %></span>
          <% end %>
        </li>

        <li>
          <%= link_to links_path do %>
            <i class="fas fa-link fa-2x"></i>
            <span><%= t("menu.link") %></span>
          <% end %>
        </li>

        <li>
          <%= link_to geems_path do %>
            <i class="fas fa-gem fa-2x"></i>
            <span><%= t("menu.geem") %></span>
          <% end %>
        </li>
      </ul>
    </div>
    <!-- #Menu -->
  </aside>
  <!-- #END# Left Sidebar -->
  <%= render 'shared/right_nav' %>
</section>

app/views/shared/_modal.html.erb
<div class="modal fade" id="defaultModal" tabindex="-1" role="dialog" style="margin-top: 5%;">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="defaultModalTitle"></h4>
      </div>
      <div class="modal-body" id="defaultModalBody">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-klink waves-effect" data-dismiss="modal">关闭</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_top_nav.html.erb
<!-- Search Bar -->
<div class="search-bar">
    <div class="search-icon">
        <i class="material-icons">search</i>
    </div>
    <input type="text" placeholder="请输入关键词...">
    <div class="close-search">
        <i class="material-icons">close</i>
    </div>
</div>
<!-- #END# Search Bar -->
<nav class="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
      <a href="javascript:void(0);" class="bars"></a>
      <a class="navbar-brand" href="javascript:void(0);"><%= Setting.app_name %> - <%= Setting.app_slogan %></a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="javascript:void(0);" class="js-search" data-close="true"><i class="material-icons">search</i></a></li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <%= material_icon.power_settings_new %>
          <% end %>
        </li>
        <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="material-icons">more_vert</i></a></li>
      </ul>
    </div>
  </div>
</nav>